// <auto-generated />
using System;
using KvizCommando.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KvizCommando.Server.Data.Migrations.SqlServer.Application
{
    [DbContext(typeof(SqlServerApplicationDbContext))]
    [Migration("20260820132120_ProfileSchemaSqlServerApplication")]
    partial class ProfileSchemaSqlServerApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_AspNetUserTokens_ExpiresAt");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Billing.UserPaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CardLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethodToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDefault")
                        .HasDatabaseName("IX_UserPaymentMethods_User_IsDefault");

                    b.ToTable("UserPaymentMethods", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Compliance.MarketingConsent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Granted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ChangedAtUtc")
                        .HasDatabaseName("IX_MarketingConsents_UserId_ChangedAtUtc");

                    b.ToTable("MarketingConsents", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Compliance.TermsConsent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("IpHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("UserAgentHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AcceptedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_TermsConsents_UserId_AcceptedAtUtc");

                    b.HasIndex("UserId", "TermsVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_TermsConsents_UserId_TermsVersion");

                    b.ToTable("TermsConsents", null, t =>
                        {
                            t.HasCheckConstraint("CK_TermsConsents_IpHash_Len", "IpHash IS NULL OR DATALENGTH(IpHash) = 32");

                            t.HasCheckConstraint("CK_TermsConsents_UserAgentHash_Len", "UserAgentHash IS NULL OR DATALENGTH(UserAgentHash) = 32");
                        });
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Players.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("CaptainAvatar")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int>("DevPoint")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedTeamName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RankEnum")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TeamNameChangedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Voucher")
                        .HasColumnType("int");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("Credit")
                        .HasDatabaseName("IX_Players_Credit");

                    b.HasIndex("NormalizedTeamName")
                        .IsUnique()
                        .HasDatabaseName("UX_Players_NormalizedTeamName");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Players_UserId");

                    b.HasIndex("XP")
                        .HasDatabaseName("IX_Players_XP");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Players.PlayerCharacter", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("CandidatesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharactersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerCharacters", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerCharacters_CandidatesJson_Valid", "ISJSON([CandidatesJson]) = 1");

                            t.HasCheckConstraint("CK_PlayerCharacters_CharactersJson_Valid", "ISJSON([CharactersJson]) = 1");
                        });
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Players.PlayerLoadout", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("FactorySlotsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpLevelsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PendingSlotsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserSlotsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerLoadouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayerLoadouts_FactorySlots_Json", "ISJSON([FactorySlotsJson]) = 1");

                            t.HasCheckConstraint("CK_PlayerLoadouts_PendingSlots_Json", "ISJSON([PendingSlotsJson]) = 1");

                            t.HasCheckConstraint("CK_PlayerLoadouts_UserSlots_Json", "ISJSON([UserSlotsJson]) = 1");
                        });
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Security.UserPii", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("BillingAddressEncrypted")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("BillingAddressNonce")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("BillingAddressTag")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("BillingNameEncrypted")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("BillingNameNonce")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("BillingNameTag")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PhoneEncrypted")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PhoneNonce")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PhoneTag")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserPii", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Statistics.PlayerAskStats", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("AveragePointsPerAsk")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(9,2)")
                        .HasComputedColumnSql("CAST(CASE WHEN [TotalQuestionsAsked] = 0 THEN 0.0 ELSE ([TotalAskPointsEarned] * 1.0 / [TotalQuestionsAsked]) END AS decimal(9,2))", true);

                    b.Property<int>("TotalAskPointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestionsAsked")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("AveragePointsPerAsk")
                        .HasDatabaseName("IX_PlayerAskStats_AvgPoints_DESC");

                    b.ToTable("PlayerAskStats", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Statistics.PlayerCategoryStat", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<int>("Answered")
                        .HasColumnType("int");

                    b.Property<int>("Correct")
                        .HasColumnType("int");

                    b.Property<int>("HighScore")
                        .HasColumnType("int");

                    b.Property<double>("HighScoreTime")
                        .HasColumnType("float");

                    b.Property<decimal>("Ratio")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(9,4)")
                        .HasComputedColumnSql("CAST(CASE WHEN [Answered] = 0 THEN 0.0 ELSE ([Correct] * 1.0 / [Answered]) END AS decimal(9,4))", true);

                    b.HasKey("PlayerId", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_PlayerCategoryStats_CategoryId");

                    b.HasIndex("Ratio")
                        .HasDatabaseName("IX_PlayerCategoryStats_Ratio_DESC");

                    b.ToTable("PlayerCategoryStats", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Statistics.PlayerOrientStat", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<short>("OrientId")
                        .HasColumnType("smallint");

                    b.Property<int>("HighScore")
                        .HasColumnType("int");

                    b.Property<double>("HighScoreTime")
                        .HasColumnType("float");

                    b.HasKey("PlayerId", "OrientId");

                    b.HasIndex("OrientId")
                        .HasDatabaseName("IX_PlayerOrientStat_CategoryId");

                    b.ToTable("PlayerOrientStat", (string)null);
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Statistics.TeamStatistic", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RankedGuessCount")
                        .HasColumnType("int");

                    b.Property<decimal>("RankedGuessErrorRatio")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,4)")
                        .HasComputedColumnSql("CAST(CASE WHEN [RankedGuessCount] = 0 THEN 0.0 ELSE ([RankedGuessErrorTotal] / [RankedGuessCount]) END AS decimal(18,4))", true);

                    b.Property<decimal>("RankedGuessErrorTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RankedHighScore")
                        .HasColumnType("float");

                    b.Property<double>("RankedHighScoreTime")
                        .HasColumnType("float");

                    b.Property<string>("RankedPlacementsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankedPlayed")
                        .HasColumnType("int");

                    b.Property<int>("RankedWon")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("RankedGuessErrorRatio")
                        .HasDatabaseName("IX_TeamStatistics_RankedGuessErrorRatio");

                    b.HasIndex("RankedHighScore", "RankedHighScoreTime")
                        .IsDescending(true, false)
                        .HasDatabaseName("IX_TeamStatistics_RankedHighScore_Time");

                    b.ToTable("TeamStatistics", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeamStatistics_RankedPlacementsJson_Valid", "ISJSON([RankedPlacementsJson]) = 1");
                        });
                });

            modelBuilder.Entity("KvizCommando.Server.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("bit");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("hu-HU");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique()
                        .HasDatabaseName("UX_AspNetUsers_NormalizedDisplayName_Active")
                        .HasFilter("[NormalizedDisplayName] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ApplicationUserToken", b =>
                {
                    b.HasOne("KvizCommando.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Security.UserPii", b =>
                {
                    b.HasOne("KvizCommando.Server.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("KvizCommando.Server.Domain.Entities.Security.UserPii", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KvizCommando.Server.Domain.Entities.Statistics.TeamStatistic", b =>
                {
                    b.HasOne("KvizCommando.Server.Domain.Entities.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("KvizCommando.Server.Domain.Entities.Statistics.TeamStatistic", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KvizCommando.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KvizCommando.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KvizCommando.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
